[package]
name = "laptop-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
device_query = "2.1.0"
libc = "0.2.161"
embedded_hal_0_2 = {package = "embedded-hal", version = "0.2.5", features = ["unproven"]}


[build-dependencies]
cc = "1.0"
